# Generated by Django 6.0 on 2025-12-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('web_design', 'Основы веб-дизайна'), ('database_design', 'Основы проектирования баз данных'), ('algorithms_programming', 'Основы алгоритмизации и программирования')], max_length=50)),
                ('date_start', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Ещё не начал'), ('in_progress', 'Начал'), ('finished', 'Завершил')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
