# Generated by Django 6.0 on 2025-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
