# Generated by Django 6.0 on 2025-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courserequest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
